### ISSUE TITLE
Organização de Materiais de  Estudo

### ISSUE THREAD

**Issue by Sleshes** [pyladiesdf/Materiais-de-Estudo#3]
Issue para discutirmos a organização dos nossos materiais de estudo/ materiais recomendados por nós

**Comment by Sleshes** [comment]
Sugestão: No readme pode ter um breve texto introdutório e no final como alguém pode requisitar um PR no formato que nós definirmos do markdown. Assim facilita que outras pessoas do grupo possam colaborar também com a lista.

por exemplo algo como  https://github.com/leticiadasilva/por-onde-comecar

**Comment by Sleshes** [comment]
@fabiolamfleury eu complementei alguns links no arquivo que você havia criado. Queria ver sua opinião quanto a organização

**Comment by fabiolamfleury** [comment]
Acho que seria bem legal essa organização do readme, pra convidar mais pessoas a colaborarem. Onde você colocou esses links? To meio perdida


Ps: vi seu commit agora, achei legal você ter colocado autoria dos materiais e essa nova divisão ;)
